<a href="https://colab.research.google.com/github/youseop/group-assignment/blob/master/%EC%A1%B0%EB%B0%B0%EC%A0%95_%EB%9E%9C%EB%8D%A4%EB%9F%B0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 조 배정 (랜덤 런치) - 중복 X



In [94]:
import pandas as pd
import numpy as np
import random, math
import sys
from collections import deque 

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### 겹치는 학생 추출


In [95]:
###### 변수 설정 #######
student_num = 30 + 2
group_num = 8
student_per_group = 4
week_num = 10

#name[0] == 'ㅇㅇㅇ' 유지시켜주세요!
name = ['ㅇㅇㅇ','고재헌','강민규','김강산','김동은','김보석','김승현','김영동','김용기','김용욱','김유석','김정민','김형우','오태양','윤준영','이병호','이승민','이유섭','정우성','조성현','조영후','조정훈','최교진','최성현','허승','김나현','김홍지','송예은','조새힘','한정서','황수정']
########################

overlap = list(set() for _ in range(student_num))

for i in range(1, week_num):
  path = path = '/content/drive/MyDrive/Deeplearning_pract/조배정프로그램/result_lunch/week_%d' %(i)
  prev_group = pd.read_csv(path, header = None)
  prev_group = prev_group.values
  
  for i in range(group_num):
    for j in range(student_per_group):
      prev_group[i][j] = name.index(prev_group[i][j])
  
  for group_x in prev_group:
    for x in group_x:
      if x != 0:
        for y in group_x:
          if y != 0:
            overlap[x].add(y)

overlap[1]

{1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 15, 16, 17, 18, 20, 22, 24, 27, 28, 29}

### 중복 허용 


In [96]:
########## 중복 허용 설정 #############
value = 1               # 중복 허용 X #
######################################

print('student per group : ', student_per_group)

sample_tmp = list(i  if i < len(name) else 0 for i in range(1, student_num+1))

for _ in range(10000000):
  random.shuffle(sample_tmp)
  sample=deque(sample_tmp)
  new_group = [sample.popleft()] #새로운 그룹 저장
  success = False #성공여부
  for i in range(1,student_num):
    #현재 new_group은 1차원 배열이기 때문에 같은 조만 탐색해야한다.
    should_check = i % student_per_group
    for _ in range(len(sample)):
      cnt_overlap = 0

      #그룹 내에서 겹치는 사람이 있는지 탐색
      for k in range(1,1+should_check):
        if set([new_group[i-k]]) & overlap[sample[0]]: 
          cnt_overlap += 1
        
      if cnt_overlap > value:
        sample.append(sample.popleft())
      else:
        new_group.append(sample.popleft())
        break
    else:
      break
  if len(new_group) == student_num:
    success = True
    break

if success:
  success_group = np.reshape(new_group,(group_num,student_per_group))
  print('\nnew group: \n',success_group)

  overlap_new = list(set() for _ in range(student_num))
  for group in success_group:
    for x in group:
      for y in group:
        overlap_new[x].add(y)
  for i in range(student_num):
    overlap_new[i] &= overlap[i]
  
  #print(overlap_new)

  checked = True
  for x in range(len(overlap_new)):
    if len(overlap_new[x]) > 1+value:
      checked = False
  if checked:
    print('\nchecked')



else:
  print('falied,,,')

student per group :  4

new group: 
 [[28 16  0 30]
 [21  7  5 22]
 [25  9 13  0]
 [ 1 12 19 23]
 [ 6 17 10  8]
 [15 18  3 29]
 [ 4 24 27 11]
 [14  2 20 26]]


### save as a file


In [97]:
for i in range(len(new_group)):
  new_group[i] = name[new_group[i]]
new_group = np.reshape(new_group,(group_num,student_per_group))
new_group = pd.DataFrame(new_group)

path = '/content/drive/MyDrive/Deeplearning_pract/조배정프로그램/result_lunch/week_%d' %(week_num)
new_group.to_csv(path, header = None, index = None)

print('\n %d 조 배치 완료!' %(week_num))



 10 조 배치 완료!
